const fs = require("fs");
const vm = require("vm");

const source = fs.readFileSync("app.js", "utf8");
const dataSource = source.slice(0, source.indexOf("const els =")) + "\nresult = stages;";
const context = {
  result: null,
  console,
  explainChoice: () => "",
  getExplanationTip: () => "",
  IMPROVEMENT_QUESTIONS: require("../improvement-questions.js"),
  SUBJECT_B_CASE_QUESTIONS: require("../subject-b-case-questions.js"),
  SUBJECT_B_CASE_QUESTIONS_2: require("../subject-b-case-questions-2.js"),
  SAMPLE_DERIVED_QUESTIONS: require("../sample-derived-questions.js"),
  QUESTION_CHOICE_SETS: fs.existsSync("question-choice-sets.js") ? require("../question-choice-sets.js") : {}
};
vm.createContext(context);
vm.runInContext(dataSource, context);

const definitions = {};
context.result.forEach((stage) => {
  stage.questions.forEach((question) => {
    const correct = question.choices[question.answer];
    definitions[question.text] = {
      stageId: stage.id,
      tag: question.tag,
      correct,
      distractors: question.choicePool || question.choices.filter((_, index) => index !== question.answer),
      ...(Object.keys(question.choiceNotes || {}).length ? { choiceNotes: question.choiceNotes } : {})
    };
  });
});

const output = `// Generated by tools/export_question_choice_sets.js.
// Edit this file to manage the correct answer and distractors for each question.
// Add at least three distractors. Six or more allows varied choices between challenges.
globalThis.QUESTION_CHOICE_SETS = ${JSON.stringify(definitions, null, 2)};

if (typeof module !== "undefined") module.exports = globalThis.QUESTION_CHOICE_SETS;
`;

fs.writeFileSync("question-choice-sets.js", output);
console.log(`Exported ${Object.keys(definitions).length} per-question choice sets.`);
